on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run generator
        uses: ./
        with:
          confluence-domain: ${{ vars.CONFLUENCE_DOMAIN }}
          confluence-username: ${{ secrets.CONFLUENCE_USERNAME }}
          confluence-token: ${{ secrets.CONFLUENCE_TOKEN }}
          confluence-space: ${{ vars.CONFLUENCE_SPACE }}
